### PR TITLE
Do not save duplicate inputs

### PR DESCRIPTION
**Pull request by realivanjx**
Just an idea to mimic the linux shell behavior. Remove empty history is also merge with this one.

Example input:
```
apple
mango
mango
mango
apple
```
The history will just be:
```
apple
mango
apple
```

### CODE REVIEW

**Comment by waf** [comment]
This (and your other PR https://github.com/waf/PrettyPrompt/pull/2) both look really good, thanks for opening them, and thanks especially for writing tests! 👍 

> Btw somehow console.StubInput($"Hello World{Enter}{Enter}{Enter}"); does not simulate multiple Enters so i have to do it like what i did in the tests.

That `StubInput` method just stubs a single prompt's input, so calling it multiple times the way you did, to simulate multiple prompts, is correct.

I'm thinking I'll merge this PR, since it has more advanced (and better for users) behavior. Let me know if you disagree. I'm really busy at work right now, but I'll get to it in the next ~24 hours. Thanks again!

**Comment by realivanjx** [comment]
yes i think you can just ignore the first pr

**Comment by waf** [comment]
Thanks, I've pulled this down and played with it, tried to break it, etc. Let's ship it :shipit:

**Comment by waf** [comment]
Version 0.9.4 (pending release on NuGet) will contain this fix/feature, thanks! Also added you to the [CONTRIBUTORS.md](https://github.com/waf/PrettyPrompt/blob/main/CONTRIBUTORS.md)

**Comment by waf** [comment]
I've pulled in the updated dependency to csharprepl, so you can enjoy this feature after you update to v0.2.1:

```
dotnet tool update -g csharprepl
```

Thanks!

**Pull request merged**
